### ISSUE TITLE
Timer on Automatic function

### ISSUE THREAD

**Issue by book0-0worm** [C20H12/Soysauce#1]
It would be nice if the time it takes to solve one question was a little longer. When I counted, it takes about 20 seconds for the whole timer to run out, so if the auto solver waited around 10~15 seconds randomly every question instead of the 2 ish seconds now, it would yield more believable results as well as show some ambiguity in the intervals you are getting the questions "right".

**Comment by C20H12** [comment]
In the file `functions.js`, there the wait times are defined in an object. [link](https://github.com/C20H12/Soysauce/blob/69ce523902989bcdbd50cfdb564b3a922206996b/extension/scripts/functions.js#L226)
  
```
const timeouts = {
          question: 3000,
          word: 5000
}
```
Right now only 2 types of situations are considered, a normal question, or a word page / the page that ask you to spell it out after a new word.  
If you want to customize it, you can change those numbers to something else. They are in miliseconds. Or even put `Math.floor(Math.random() * (maxSeconds - minSeconds) * 1000) + minSeconds * 1000` for even more randomness.  

But this will be a planned addition for the customizing menu, which will be added in a future update.

**Comment by C20H12** [comment]
Added. Will be included in the next release.
